version: "1"
rules:                                      # Array of rules
  - base: main                              # Required. Target branch
    upstream: krotscheck:main               # Required. Must be in the same fork network.
    mergeMethod: squash                     # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: false                    # Optional, merge pull request even when the mergeable_state is not clean. Default: false
    assignees:
      - krotscheck
      - wei
    reviewers:
      - 1x-eng
    conflictReviewers:
      - 1x-eng
label: ":arrow_heading_down: pull"          # Optional
conflictLabel: "fork-sync-merge-conflict"   # Optional, on merge conflict assign a custom label, Default: merge-conflict